### ISSUE TITLE
Doesn't seem working in 10.8.0

### ISSUE THREAD

**Issue by kimpig** [jellyfin/jellyfin-plugin-fanart#42]
It worked up to Jellyfin version 10.7.7, but from 10.8.0 it fails to import images.

Jellyfin Version : 10.8.0
Fanart Plugin Version : 9.0.0

**Comment by crobibero** [comment]
What is the experience you're having?
Is there anything in the logs?

**Comment by kimpig** [comment]
https://www.reddit.com/r/jellyfin/comments/vakjxk/fanart_plugin_is_not_working/
https://github.com/jellyfin/jellyfin-plugin-fanart/pull/38

It seems that this problem will be fixed in v10.0.0, is that correct?

**Comment by crobibero** [comment]
Yes, please try plugin v10 - it should be available now

**Comment by kimpig** [comment]
Thanks, it's working now.
I have one more question, what is a Personal API Key? No information is displayed when I click LearnMore.

**Comment by crobibero** [comment]
I found this article that has roughly the same title: https://medium.com/fanart-tv/what-are-fanart-tv-personal-api-keys-472f60222856

**Comment by kimpig** [comment]
Oh, I found it.
I think LearnMore should link to this
https://fanart.tv/get-an-api-key/
