### ISSUE TITLE
Causes Jellyfin to restart when idle

### ISSUE THREAD

**Issue by scicomrunner** [jellyfin/jellyfin-plugin-fanart#5]
After installing this plugin in 10.4.0 on Linux Jellyfin will restart when idle and crash.
From the plugin page I select version 2 to be installed. Restart Jellyfin to load the plugin. Version 1.1 is reported to be installed. I can use the plugin and Jellyfin with out any issue. Once I let Jellyfin sit idle for about an hour or so it will log it needs to restart and crashes (fails auto-restart), I then have to manually start the jellyfin service again.  After removing this plugin Jellyfin has been running without having to manual start the service every hour or so.

.......
[INF] Plugin updated: Fanart 2.0 Release
[INF] App needs to be restarted.
[INF] Check for plugin updates Completed after 0 minute(s) and 1 seconds
.........
[INF] Automatically restarting the system because it is idle and a restart is required.

**Comment by anthonylavado** [comment]
It sounds like there’s a permission issue, as the app is literally supposed to delete the old plugin when you update.

Try and remove the original version, and confirm it goes away. Then, install version 2.

**Comment by anthonylavado** [comment]
Actually, it seems it is a version numbering issue. We've got a fix in, the build should be kicking off shortly.

**Comment by anthonylavado** [comment]
@scicomrunner You should be able to install version 3 without issue :-)

**Comment by scicomrunner** [comment]
I have the new version installed and loaded and seems to be stable, no hourly restarts.
